name: Java CI with Gradle

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Choose the JDK version (you can change it)

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon  # Command to build the Gradle project

    - name: Run tests
      run: ./gradlew test --no-daemon  # Command to run tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests  # Path to test reports
